char defaults_string[] = 
  "### ENZO DEFAULT PARAMETER VALUES ###\n"
  "\n"
  "Internal:\n"
  "{\n"
  "	Fields = [\"Density\", \"X-velocity\", \"Y-velocity\", \"Z-velocity\", \"TotalEnergy\", \"GasEnergy\", \"Bx\", \"By\", \"Bz\", \"Phi\", \"ElectronDensity\", \"HI_Density\", \"HII_Density\", \"HeI_Density\", \"HeII_Density\", \"HeIII_Density\", \"HM_Density\", \"H2I_Density\", \"H2II_Density\", \"DI_Density\", \"DII_Density\", \"HDI_Density\"];\n"
  "\n"
  "	Density:\n"
  "	{\n"
  "		Name = \"Density\";\n"
  "		cgsConversionFactor = \"2.29415e-26\";\n"
  "	};	\n"
  "	X-velocity:\n"
  "	{\n"
  "		Name = \"x-velocity\";\n"
  "		cgsConversionFactor = \"1.94115e+07\";\n"
  "	};\n"
  "	Y-velocity:\n"
  "	{\n"
  "		Name = \"y-velocity\";\n"
  "		cgsConversionFactor = \"1.94115e+07\";\n"
  "	};\n"
  "	Z-velocity:\n"
  "	{\n"
  "		Name = \"z-velocity\";\n"
  "		cgsConversionFactor = \"1.94115e+07\";\n"
  "	};\n"
  "	TotalEnergy:\n"
  "	{\n"
  "		Name = \"Totalenergy\";\n"
  "		cgsConversionFactor = \"\";\n"
  "	};\n"
  "	GasEnergy:\n"
  "	{\n"
  "		Name = \"GasEnergy\";\n"
  "		cgsConversionFactor = \"\";\n"
  "	};\n"
  "	Bx:\n"
  "	{\n"
  "		Name = \"Bx\";\n"
  "		cgsConversionFactor = \"\";\n"
  "	};\n"
  "	By:\n"
  "	{\n"
  "		Name = \"By\";\n"
  "		cgsConversionFactor = \"\";\n"
  "	};\n"
  "	Bz:\n"
  "	{\n"
  "		Name = \"Bz\";\n"
  "		cgsConversionFactor = \"\";\n"
  "	};\n"
  "	Phi:\n"
  "	{\n"
  "		Name = \"Phi\";\n"
  "		cgsConversionFactor = \"\";\n"
  "	};\n"
  "	ElectronDensity:\n"
  "	{\n"
  "		Name = \"Electron_Density\";\n"
  "		cgsConversionFactor = \"2.29415e-26\";\n"
  "	};\n"
  "	HI_Density:\n"
  "	{\n"
  "		Name = \"HI_Density\";\n"
  "		cgsConversionFactor = \"2.29415e-26\";\n"
  "	};\n"
  "	HII_Density:\n"
  "	{\n"
  "		Name = \"HII_Density\";\n"
  "		cgsConversionFactor = \"2.29415e-26\";\n"
  "	};\n"
  "	HeI_Density:\n"
  "	{\n"
  "		Name = \"HeI_Density\";\n"
  "		cgsConversionFactor = \"2.29415e-26\";\n"
  "	};\n"
  "	HeII_Density:\n"
  "	{\n"
  "		Name = \"HeII_Density\";\n"
  "		cgsConversionFactor = \"2.29415e-26\";\n"
  "	};\n"
  "	HeIII_Density:\n"
  "	{\n"
  "		Name = \"HeIII_Density\";\n"
  "		cgsConversionFactor = \"2.29415e-26\";\n"
  "	};\n"
  "	HM_Density:\n"
  "	{\n"
  "		Name = \"HM_Density\";\n"
  "		cgsConversionFactor = \"2.29415e-26\";\n"
  "	};\n"
  "	H2I_Density:\n"
  "	{\n"
  "		Name = \"H2I_Density\";\n"
  "		cgsConversionFactor = \"2.29415e-26\";\n"
  "	};\n"
  "	H2II_Density:\n"
  "	{\n"
  "		Name = \"H2II_Density\";\n"
  "		cgsConversionFactor = \"2.29415e-26\";\n"
  "	};\n"
  "	DI_Density:\n"
  "	{\n"
  "		Name = \"DI_Density\";\n"
  "		cgsConversionFactor = \"2.29415e-26\";\n"
  "	};\n"
  "	DII_Density:\n"
  "	{\n"
  "		Name = \"DII_Density\";\n"
  "		cgsConversionFactor = \"2.29415e-26\";\n"
  "	};\n"
  "	HDI_Density:\n"
  "	{\n"
  "		Name = \"HDI_Density\";\n"
  "		cgsConversionFactor = \"2.29415e-26\";\n"
  "	};\n"
  "	TimeUnits:\n"
  "	{\n"
  "		Name = \"TimeUnits\";\n"
  "		cgsConversionFactor = \"6.80582e+14\";\n"
  "	};\n"
  "	TemperatureUnits:\n"
  "	{\n"
  "		Name = \"TemperatureUnits\";\n"
  "		cgsConversionFactor = \"4.72068e+06\";\n"
  "	};\n"
  "\n"
  "	Provenance:\n"
  "	{\n"
  "		MetaDataIdentifier      = \"\";\n"
  "		SimulationUUID          = \"\";\n"
  "#		DatasetUUID             = \"\";\n"
  "		RestartDatasetUUID      = \"\";\n"
  "		InitialConditionsUUID   = \"\";\n"
  "		VersionNumber           = \"2.0\";\n"
  "	};\n"
  "\n"
  "	OutputLabeling:\n"
  "	{\n"
  "		TimeLastRestartDump = 0.0;\n"
  "		TimeLastDataDump    = -99999.0;\n"
  "		TimeLastHistoryDump = -99999.0;\n"
  "		TimeLastTracerParticleDump = -99999.0;\n"
  "		TimeLastInterpolatedDataDump    = -99999.0;\n"
  "		MovieTimestepCounter = 0;\n"
  "		CycleLastRestartDump = 0;\n"
  "		CycleLastDataDump    = -99999;\n"
  "		CycleLastHistoryDump = -99999;\n"
  "		SubcycleLastDataDump    = -99999;\n"
  "		RestartDumpNumber   = 0;\n"
  "		DataDumpNumber      = 0;\n"
  "		HistoryDumpNumber   = 0;\n"
  "		TracerParticleDumpNumber = 0;\n"
  "		CheckpointRestart   = False;\n"
  "	};\n"
  "\n"
  "	InitialCycleNumber  = 0;\n"
  "	SubcycleNumber      = 0;\n"
  "	InitialTime         = 0.0;\n"
  "	Initialdt           = 0.01;\n"
  "	InitialCPUTime      = 0.0;\n"
  "	NumberOfParticles      = 0;\n"
  "	Debug1                          = False;\n"
  "	Debug2                          = False;\n"
  "	CosmologyCurrentRedshift   = -99999.0;\n"
  "	BoundaryConditionName      = \"\";\n"
  "};\n"
  "\n"
  "\n"
  "SimulationControl: # (subgroup refinement for later on)\n"
  "{\n"
  "	StopTime            = -99999.0;\n"
  "	StopCycle           = 100000;\n"
  "	StopSteps           = 10000;\n"
  "	StopCPUTime         = 2592000.0;  # 30 days\n"
  "	ResubmitOn          = False;\n"
  "	ResubmitCommand     = \"\";\n"
  "	MaximumTopGridTimeStep = 1e20;\n"
  "	TracerParticleOn           = False;\n"
  "	StopFirstTimeAtLevel    = 0;\n"
  "	UseCUDA                        = False;\n"
  "	huge_number                    = 1.000000e20;\n"
  "	tiny_number                    = 1.000000e-20;\n"
  "\n"
  "	Domain:\n"
  "	{\n"
  "		TopGridRank         = -99999;\n"
  "		TopGridDimensions   = [-99999, -99999, -99999];\n"
  "		LeftFaceBoundaryCondition  = [0, 0, 0];\n"
  "		RightFaceBoundaryCondition = [0, 0, 0];\n"
  "		RefineRegionLeftEdge   = [-99999.0, -99999.0, -99999.0];\n"
  "		RefineRegionRightEdge  = [-99999.0, -99999.0, -99999.0];\n"
  "		DomainLeftEdge         = [0.0, 0.0, 0.0] ;\n"
  "		DomainRightEdge        = [1.0, 1.0, 1.0];\n"
  "		RefineRegionAutoAdjust = False;\n"
  "		MustRefineRegionLeftEdge = [0.0, 0.0, 0.0]; \n"
  "		MustRefineRegionRightEdge  = [1.0, 1.0, 1.0]; \n"
  "	};\n"
  "	\n"
  "	AMR:\n"
  "	{\n"
  "		RefineBy                       = 2;\n"
  "		MaximumRefinementLevel         = 2;\n"
  "		MaximumGravityRefinementLevel  = -99999;\n"
  "		MaximumParticleRefinementLevel = -1;\n"
  "		NumberOfBufferZones            = 1;\n"
  "		StaticHierarchy                = True;\n"
  "		CellFlaggingMethod             = [-99999, -99999, -99999, -99999, -99999, -99999, -99999, -99999, -99999];\n"
  "		RefineByJeansLengthSafetyFactor  = 4.0;\n"
  "		JeansRefinementColdTemperature  = -1.0;\n"
  "		RefineByResistiveLengthSafetyFactor  = 2.000000;\n"
  "		MustRefineParticlesRefineToLevel = False;\n"
  "		MustRefineParticlesRefineToLevelAutoAdjust = False;\n"
  "		MustRefineParticlesMinimumMass = 0.0;\n"
  "		MustRefineRegionMinRefinementLevel  = -1;\n"
  "		MetallicityRefinementMinLevel       = -1;\n"
  "		MetallicityRefinementMinMetallicity = 1e-05;\n"
  "		MetallicityRefinementMinDensity     = -99999.0;\n"
  "		RefineRegionTimeType   = -1;\n"
  "		SlopeFlaggingFields = [-99999, -99999, -99999, -99999, -99999, -99999, -99999, -99999, -99999];\n"
  "		MinimumSlopeForRefinement = [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3];\n"
  "		MinimumOverDensityForRefinement = [1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5];\n"
  "		MinimumMassForRefinement = [-99999.0, -99999.0, -99999.0, -99999.0, -99999.0, -99999.0, -99999.0, -99999.0, -99999.0];\n"
  "		MinimumMassForRefinementLevelExponent = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0];\n"
  "		MinimumShearForRefinement             = 1.0;\n"
  "		MinimumPressureJumpForRefinement      = 0.33;\n"
  "		MinimumEnergyRatioForRefinement       = 0.1;\n"
  "		ShockwaveRefinementMinMach            = 1.3;\n"
  "		ShockwaveRefinementMinVelocity        = 1.0e7;\n"
  "		ShockwaveRefinementMaxLevel           = 0;\n"
  "		RefineByJeansLengthUnits              = False;\n"
  "	\n"
  "		StaticRefineRegion:\n"
  "		{\n"
  "			Regions=[];\n"
  "		};\n"
  "\n"
  "		RefineRegionFile = \"\";\n"
  "	\n"
  "	\n"
  "	}; # end amr\n"
  "\n"
  "	Optimization:\n"
  "	{\n"
  "\n"
  "		LoadBalancing          = 1;\n"
  "		ResetLoadBalancing     = False;\n"
  "		LoadBalancingCycleSkip = 10;\n"
  "		LoadBalancingMinLevel  = 0;\n"
  "		LoadBalancingMaxLevel  = 50;\n"
  "		RadiativeTransferLoadBalance    = False;\n"
  "		ParallelRootGridIO              = False;\n"
  "		ParallelParticleIO              = False;\n"
  "		Unigrid                         = False;\n"
  "		UnigridTranspose                = False;\n"
  "		MinimumEfficiency              = 0.2;\n"
  "		SubgridSizeAutoAdjust          = True;\n"
  "		OptimalSubgridsPerProcessor    = 16;\n"
  "		MinimumSubgridEdge             = 6;\n"
  "		MaximumSubgridSize             = 32768;\n"
  "		NumberOfRootGridTilesPerDimensionPerProcessor = 1;\n"
  "		MoveParticlesBetweenSiblings     = True;\n"
  "		ParticleSplitterIterations       = False;\n"
  "		ParticleSplitterChildrenParticleSeparation     = 1.0;\n"
  "		MemoryLimit                     = 4000000000;\n"
  "		FastSiblingLocatorEntireDomain      = True;\n"
  "	};\n"
  "\n"
  "	Units:\n"
  "	{\n"
  "		Mass = 1.0;\n"
  "		Density = 1.0;\n"
  "		Length = 1.0;\n"
  "		Time = 1.0;\n"
  "	};\n"
  "\n"
  "	Timeaction:\n"
  "	{\n"
  "		Actions = [];\n"
  "	};\n"
  "\n"
  "}; # end SimulationControl\n"
  "\n"
  "\n"
  "\n"
  "OutputControl:\n"
  "{\n"
  "\n"
  "	dtInterpolatedDataDump       = 0.0;\n"
  "	FileDirectedOutput           = True;\n"
  "	WriteBinaryHierarchy         = False;\n"
  "	GlobalDir                    = \"\";\n"
  "	LocalDir                     = \"\";\n"
  "	ParticleTypeInFile           = True;\n"
  "	OutputParticleTypeGrouping   = False;\n"
  "	ExtractFieldsOnly            = True;\n"
  "	CubeDumpEnabled              = False;  #(remove confirmed)\n"
  "\n"
  "\n"
  "	DataDump:\n"
  "	{\n"
  "		Name = \"data\";\n"
  "		Dir  = \"DD\";\n"
  "		dt   = 0.0;\n"
  "	};\n"
  "\n"
  "	RestartDump:\n"
  "	{\n"
  "		Name = \"restart\";\n"
  "		Dir  = \"RS\";\n"
  "		dt   = -99999.0;\n"
  "	};\n"
  "\n"
  "	MovieDump:\n"
  "	{\n"
  "		Name                  = \"MoviePack\";\n"
  "		LeftEdge              = [0.0, 0.0, 0.0];\n"
  "		RightEdge             = [1.0, 1.0, 1.0];\n"
  "		SkipTimestep          = -99999;\n"
  "		Volumes3D             = False;\n"
  "		VertexCentered        = False;\n"
  "		ParticleOn            = False;\n"
  "		DataField             = [-99999, -99999, -99999, -99999, -99999, -99999];\n"
  "		DumpNumber            = 0;\n"
  "	};\n"
  "\n"
  "	CycleDump:\n"
  "	{\n"
  "		SkipRestartDump = 0;\n"
  "		SkipDataDump    = 0;\n"
  "		SkipHistoryDump = 0;\n"
  "	        SkipGlobalDataDump = 0;\n"
  "		SubcycleSkipDataDump    = 0;\n"
  "	};\n"
  "\n"
  "	RedshiftDump:\n"
  "	{\n"
  "		Name        = \"RedshiftOutput\";\n"
  "		Dir         = \"RD\";\n"
  "		OutputRedshifts = [];\n"
  "		OutputRedshiftNames = [];\n"
  "	};\n"
  "\n"
  "	HistoryDump:\n"
  "	{\n"
  "		Name     = \"history\";\n"
  "		Dir      = \"HD\";\n"
  "		dt       = 0.0;\n"
  "	};\n"
  "\n"
  "	TracerParticleDump:\n"
  "	{\n"
  "		Name     = \"TracerOutput\";\n"
  "		Dir      = \"TD\";\n"
  "		dt       = 0.0;\n"
  "	};\n"
  "\n"
  "	OutputTriggers:\n"
  "	{\n"
  "		OutputFirstTimeAtLevel = 0;\n"
  "		StartDensityOutputs    = -99999;\n"
  "		OutputOnDensity        = False;\n"
  "		CurrentDensityOutput   = -99999;\n"
  "		IncrementDensityOutput = -99999.0;\n"
  "	};\n"
  "\n"
  "	SupplementalFields:\n"
  "	{\n"
  "		WritePotential                 = False;\n"
  "		OutputCoolingTime              = False;\n"
  "		OutputTemperature              = False;\n"
  "		OutputSmoothedDarkMatter       = False;\n"
  "		SmoothedDarkMatterNeighbors    = 32;\n"
  "		OutputGriddedStarParticle      = False;\n"
  "		BAnyl                          = False;\n"
  "		VelAnyl                        = False;\n"
  "	};\n"
  "\n"
  "}; # end OutputControlParameters\n"
  "\n"
  "\n"
  "\n"
  "\n"
  "\n"
  "Physics:\n"
  "{\n"
  "\n"
  "	TopGridGravityBoundary     = 0;\n"
  "	ParticleBoundaryType       = 3;\n"
  "	GridVelocity               = [0.0 ,0.0, 0.0]; #(remove)\n"
  "	AccretionKernel            = 0;\n"
  "	UsePhysicalUnit            = False;\n"
  "	UseFloor                   = False;\n"
  "	SmallRho                   = 1.0e-30;\n"
  "	SmallP                     = 1.0e-35;\n"
  "	SmallT                     = 1.0e-10;\n"
  "	Coordinate                 = 0;   \n"
  "	PoissonApproximationThreshold = 0.001;\n"
  "	PoissonBoundaryType        = 0;\n"
  "\n"
  "	AngularVelocity              = 0.001;\n"
  "	VelocityGradient             = 1.0;\n"
  "	ShearingVelocityDirection    = -1;\n"
  "	ShearingBoundaryDirection    = -1;\n"
  "	ShearingBoxProblemType       = 0;\n"
  "\n"
  "	Hydro:\n"
  "	{\n"
  "		#split between ppm and zeus?\n"
  "	\n"
  "		CourantSafetyNumber    = 0.6;\n"
  "		HydroMethod            = 0;   # PPM Direct Euler\n"
  "		Gamma                  = 1.6666667;\n"
  "\n"
  "		PPMFlatteningParameter = False;\n"
  "		PPMDiffusionParameter  = False;\n"
  "		PPMSteepeningParameter = False;\n"
  "\n"
  "		EOSType                    = 0;\n"
  "		EOSSoundSpeed              = 2.65e4;\n"
  "		EOSCriticalDensity         = 1e-13;\n"
  "		EOSGamma                   = 1.6666667;\n"
  "		Mu                         = 0.6;\n"
  "\n"
  "		PressureFree                   = False;\n"
  "\n"
  "		UseMinimumPressureSupport        = False;\n"
  "		MinimumPressureSupportParameter  = 100.0;\n"
  "\n"
  "		FluxCorrection                 = True;\n"
  "		InterpolationMethod            = 1;  # SecondOrderA\n"
  "		ConservativeInterpolation      = True;\n"
  "\n"
  "		DualEnergyFormalism         = False;\n"
  "		DualEnergyFormalismEta1     = 0.001;\n"
  "		DualEnergyFormalismEta2     = 0.1;\n"
  "\n"
  "		ZEUSLinearArtificialViscosity    = 0.0;\n"
  "		ZEUSQuadraticArtificialViscosity = 2.0;\n"
  "\n"
  "		ParticleCourantSafetyNumber = 0.5;\n"
  "		RootGridCourantSafetyNumber = 1.0;\n"
  "\n"
  "		UseViscosity               = False;\n"
  "		ViscosityCoefficient       = 0.0;\n"
  "		UseAmbipolarDiffusion      = False;\n"
  "		UseResistivity             = False;\n"
  "\n"
  "		UseHydro                   = True;\n"
  "		Theta_Limiter              = 1.5;\n"
  "		RiemannSolver              = -99999;\n"
  "		RiemannSolverFallback      = False;\n"
  "		IsothermalSoundSpeed       = 1.0;\n"
  "\n"
  "		ConservativeReconstruction = True;\n"
  "		PositiveReconstruction     = False;\n"
  "		ReconstructionMethod       = -99999;\n"
  "		RKOrder                    = 2;\n"
  "	}; # end hydro\n"
  "\n"
  "	OtherParticles:\n"
  "	{\n"
  "		StarParticleCreation                  = 0;\n"
  "		StarMetalYield                        = 0.02;\n"
  "		StarMassEjectionFraction              = 0.25;\n"
  "		StarEnergyToThermalFeedback           = 1.0e-05;\n"
  "		StarEnergyToStellarUV                 = 3.0e-06;\n"
  "		StarEnergyToQuasarUV                  = 5.0e-06;\n"
  "		StellarWindFeedback                   = 0;\n"
  "		StellarWindTurnOnMass                 = 0.1;  #(please document)\n"
  "		MSStellarWindTurnOnMass               = 10.0; #(please document)\n"
  "		StarParticleFeedback                  = 0;\n"
  "		NumberOfParticleAttributes            = -99999;\n"
  "		AddParticleAttributes                 = False;\n"
  "		S2ParticleSize                        = 3.0;\n"
  "\n"
  "		StarFeedbackDistRadius                = 0;\n"
  "		StarFeedbackDistCellStep	      = 0;\n"
  "\n"
  "		BigStar:\n"
  "		{\n"
  "			Formation                      = False;\n"
  "			FormationDone		       = False;\n"
  "			Separation                     = 0.25;\n"
  "		};\n"
  "\n"
  "		StarMaker:\n"
  "		{\n"
  "			# Question: do any of the other star methods use these parameters?\n"
  "			OverDensityThreshold         = 100.0;\n"
  "			SHDensityThreshold           = 7.0e-26;\n"
  "			MassEfficiency               = 1.0;\n"
  "			MinimumMass                  = 1.0e9;\n"
  "			MinimumDynamicalTime         = 1.0e6;\n"
  "		};\n"
  "\n"
  "		PopIIIStarParticle:\n"
  "		{\n"
  "\n"
  "			StarMass                        = 100.0;\n"
  "			InitialMassFunction             = False;\n"
  "			InitialMassFunctionSeed         = -99999;\n"
  "			InitialMassFunctionCalls        = 0;\n"
  "			LowerMassCutoff                 = 1.0;\n"
  "			UpperMassCutoff                 = 300.0;\n"
  "			MassRange                       = [1.0, 300.0]; \n"
  "			InitialMassFunctionSlope        = -1.3;\n"
  "			HeliumIonization                = False;\n"
  "			BlackHoles                      = False;\n"
  "			BHLuminosityEfficiency          = 0.1;\n"
  "			OverDensityThreshold            = 1.0e6;\n"
  "			H2CriticalFraction              = 5.0e-4;\n"
  "			MetalCriticalFraction           = 1.0e-4;\n"
  "			SupernovaRadius                 = 1.0;\n"
  "			SupernovaUseColour              = False;\n"
  "			SupernovaMustRefine             = False;\n"
  "			SupernovaMustRefineResolution   = 32;\n"
  "			ColorDensityThreshold           = 1.0e6;\n"
  "			ColorMass                       = 1.0e6;\n"
  "		};\n"
  "\n"
  "		MBHParticle:\n"
  "		{	\n"
  "			Accretion                          = False;\n"
  "			AccretionRadius                    = 50.0;\n"
  "			AccretingMassRatio                 = 1.0;\n"
  "			AccretionFixedTemperature          = 3.0e5;\n"
  "			AccretionFixedRate                 = 1.0e-3;\n"
  "			TurnOffStarFormation               = False;\n"
  "			CombineRadius                      = 50.0;\n"
  "			MinDynamicalTime                   = 1.0e7;\n"
  "			MinimumMass                        = 1.0e3;\n"
  "			Feedback                           = False;\n"
  "			FeedbackRadiativeEfficiency        = 0.1;\n"
  "			FeedbackEnergyCoupling             = 0.05;\n"
  "			FeedbackMassEjectionFraction       = 0.1;\n"
  "			FeedbackMetalYield                 = 0.02;\n"
  "			FeedbackThermalRadius              = 50.0;\n"
  "			FeedbackJetsThresholdMass          = 10.0;\n"
  "		};			\n"
  "\n"
  "		StarClusterParticle:\n"
  "		{\n"
  "			UseMetalField              = False;\n"
  "			UnresolvedModel            = False;\n"
  "			MinDynamicalTime           = 1.0e7;\n"
  "			IonizingLuminosity         = 1.0e47;\n"
  "			HeliumIonization           = False;\n"
  "			SNEnergy                   = 6.8e48;\n"
  "			SNRadius                   = 10.0;\n"
  "			FormEfficiency             = 0.1;\n"
  "			MinimumMass                = 1000.0;\n"
  "			CombineRadius              = 10.0;\n"
  "			RegionLeftEdge             = [0.0, 0.0, 0.0];\n"
  "			RegionRightEdge            = [1.0, 1.0, 1.0];\n"
  "		};\n"
  "\n"
  "		SinkParticle:\n"
  "		{	\n"
  "			MergeDistance              = 1.0e16;\n"
  "			MergeMass                  = 0.1;\n"
  "		};\n"
  "\n"
  "		TracerParticle:\n"
  "		{\n"
  "			CreationSpacing            = -99999.0;\n"
  "			CreationLeftEdge           = [-99999.0, -99999.0, -99999.0];\n"
  "			CreationRightEdge          = [-99999.0, -99999.0, -99999.0];\n"
  "		};\n"
  "\n"
  "	}; # end otherParticles\n"
  "\n"
  "	Gravity:\n"
  "	{\n"
  "		UniformGravity               = False;\n"
  "		UniformGravityDirection      = 0;\n"
  "		UniformGravityConstant       = 1.0;\n"
  "		PointSourceGravity           = False;\n"
  "		PointSourceGravityPosition   = [0.0, 0.0, 0.0]; \n"
  "		PointSourceGravityConstant   = 1.0;\n"
  "		PointSourceGravityCoreRadius = 0.0;\n"
  "		ExternalGravity              = False;\n"
  "		SelfGravity                  = True;\n"
  "		SelfGravityGasOff            = False;\n"
  "		GravitationalConstant        = 12.566370614359172; # 4*pi\n"
  "		GravityResolution            = 1.0;\n"
  "		ComputePotential             = False;  #(remove confirmed)\n"
  "		PotentialIterations          = 4; #(revisit by gravity solver group)\n"
  "		BaryonSelfGravityApproximation = True;\n"
  "		GreensFunctionMaxNumber     = 1;\n"
  "		GreensFunctionMaxSize       = 1;\n"
  "		UseConstantAcceleration     = False;\n"
  "		ConstantAcceleration        = [0.0, 0.0, 0.0];\n"
  "	};\n"
  "\n"
  "\n"
  "	AtomicPhysics:\n"
  "	{	\n"
  "		MetalCooling                   = False;\n"
  "		MetalCoolingTable              = \"metal_cool.dat\";\n"
  "		CoolingCutOffDensity1          = 0.0; \n"
  "		CoolingCutOffDensity2          = 1e10; \n"
  "		CoolingCutOffTemperature       = 0.0;\n"
  "		CoolingPowerCutOffDensity1     = 0.0; \n"
  "		CoolingPowerCutOffDensity2     = 1.0e10;\n"
  "		UseH2OnDust                    = False;\n"
  "		RadiativeCooling               = True;\n"
  "		RadiativeCoolingModel          = 1;\n"
  "		GadgetEquilibriumCooling       = 0; #(is being fixed)\n"
  "		MultiSpecies                   = 0;\n"
  "		PrimordialChemistrySolver      = False;\n"
  "		CIECooling                     = True;\n"
  "		H2OpticalDepthApproximation    = True;\n"
  "		ThreeBodyRate                  = 0;\n"
  "		CoolDataf0to3                  = 0.1;\n"
  "		NumberOfTemperatureBins        = 600;\n"
  "		CoolDataIh2co                  = True;\n"
  "		CoolDataIpiht                  = True;\n"
  "\n"
  "		TemperatureStart               = 1.0;\n"
  "		TemperatureEnd                 = 1.0e8;\n"
  "\n"
  "		CoolDataCompXray               = 0.0;\n"
  "		CoolDataTempXray               = 0.0;\n"
  "		RateDataCaseBRecombination     = False;\n"
  "		PhotoelectricHeating           = False;\n"
  "		HydrogenFractionByMass         = 0.76;\n"
  "		DeuteriumToHydrogenRatio       = 6.8e-5;\n"
  "		MultiMetals                    = 0;\n"
  "\n"
  "		CloudyCooling:\n"
  "		{\n"
  "			CloudyCoolingGridFile          = \"\";\n"
  "			IncludeCloudyHeating           = False;\n"
  "			IncludeCloudyMMW               = False;\n"
  "			CMBTemperatureFloor            = True;\n"
  "			CloudyMetallicityNormalization = 0.018477;\n"
  "			CloudyElectronFractionFactor   = 9.153959e-3;\n"
  "		};\n"
  "\n"
  "	}; # end atomicPhysics\n"
  "\n"
  "	RadiationField:\n"
  "	{\n"
  "		RadiationRedshiftOn            = 7.0;\n"
  "		RadiationRedshiftOff           = 0.0;\n"
  "		RadiationRedshiftFullOn        = 6.0;\n"
  "		RadiationRedshiftDropOff       = 0.0;\n"
  "\n"
  "		RadiationFieldType             = 0;\n"
  "		TabulatedLWBackground          = False;\n"
  "		AdjustUVBackground             = True;\n"
  "		SetUVBAmplitude                = True;\n"
  "		SetHeIIHeatingScale            = 1.8;\n"
  "		RadiationFieldLevelRecompute   = False;\n"
  "		RadiationShield                = False;\n"
  "		RadiationSpectrumNormalization = 1.0e-21;\n"
  "		RadiationSpectrumSlope         = 1.5;\n"
  "\n"
  "		RadHydroParamfile = \"\";\n"
  "	};\n"
  "\n"
  "\n"
  "	Cosmology:\n"
  "	{\n"
  "		HubbleConstantNow   = 0.701;\n"
  "		OmegaMatterNow      = 0.279;\n"
  "		OmegaLambdaNow      = 0.721;\n"
  "		ComovingBoxSize     = 64.0;\n"
  "		MaxExpansionRate    = 0.01;\n"
  "		InitialRedshift     = 99.0 ; \n"
  "		FinalRedshift       = 0.0; \n"
  "		ComovingCoordinates = True;\n"
  "	};\n"
  "\n"
  "	RadiationTransfer:\n"
  "	{\n"
  "		RadiativeTransfer              = False;\n"
  "		RadiationXRaySecondaryIon      = False;\n"
  "		RadiationXRayComptonHeating    = False;\n"
  "		RadiativeTransferRadiationPressure        = False;\n"
  "		RadiativeTransferRadiationPressureScale   = 0.0;\n"
  "		RadiativeTransferSourceRadius             = 0.0;\n"
  "		RadiativeTransferPropagationSpeedFraction = 0.0;\n"
  "		RadiativeTransferPropagationDistance      = 0.0;\n"
  "		RadiativeTransferCoupledRateSolver        = False;\n"
  "		RadiativeTransferOpticallyThinH2          = False;\n"
  "		RadiativeTransferFLDCallOnLevel           = 0;\n"
  "		RadiativeTransferPeriodicBoundary         = False;\n"
  "		RadiativeTransferSplitPhotonRadius        = 0.0;\n"
  "		RadiativeTransferFluxBackgroundLimit      = 0.0;\n"
  "		RadiativeTransferRaysPerCell              = 0.0;\n"
  "		RadiativeTransferTimestepVelocityLimit    = 0.0;\n"
  "		RadiativeTransferInitialHEALPixLevel      = 0;\n"
  "		RadiativeTransferPhotonEscapeRadius       = 0.0;\n"
  "		RadiativeTransferInterpolateField         = False;\n"
  "		RadiativeTransferSourceClustering         = False;\n"
  "		RadiativeTransferPhotonMergeRadius        = 0.0;\n"
  "		RadiativeTransferSourceBeamAngle          = 0.0;\n"
  "		RadiativeTransferHIIRestrictedTimestep    = False;\n"
  "		RadiativeTransferAdaptiveTimestep         = False;\n"
  "		RadiativeTransferHydrogenOnly             = False;\n"
  "		RadiativeTransferTraceSpectrum            = False;\n"
  "		RadiativeTransferTraceSpectrumTable       = \"\";\n"
  "		dtPhoton                                  = -99999.0;\n"
  "\n"
  "		ImplicitProblem                           = False;\n"
  "		RadiativeTransferFLD                      = False;\n"
  "\n"
  "		SimpleQ                                   = 1.0e50;\n"
  "		SimpleRampTime                            = 0.1;\n"
  "	};\n"
  "\n"
  "	Conduction:\n"
  "	{\n"
  "		IsotropicConduction             = False;\n"
  "		IsotropicConductionSpitzerFraction = 1.0;\n"
  "		AnisotropicConduction           = False;\n"
  "		AnisotropicConductionSpitzerFraction = 1.0;\n"
  "		ConductionCourantSafetyNumber   = 0.5;\n"
  "	};\n"
  "\n"
  "	MHD:\n"
  "	{\n"
  "		ResetMagneticField               = False;\n"
  "		ResetMagneticFieldAmplitude      = [0.0, 0.0, 0.0];\n"
  "		MaximumAlvenSpeed                = 1.0e30;\n"
  "		DivBDampingLength                = 1.0;\n"
  "		DivergenceCleaningBoundaryBuffer = 0;\n"
  "		UseDivergenceCleaning            = False;\n"
  "		DivergenceCleaningThreshold      = 0.001;\n"
  "	};\n"
  "\n"
  "	Miscellaneous:\n"
  "	{\n"
  "		CRModel                        = False;\n"
  "		ShockMethod                    = False;\n"
  "		ShockTemperatureFloor          = 1.0;\n"
  "		StorePreShockFields            = False;\n"
  "		RandomForcing                  = False;\n"
  "		RandomForcingEdot              = 1.0;\n"
  "		RandomForcingMachNumber        = 0.0;\n"
  "		UseDrivingField                = False;\n"
  "		DrivingEfficiency              = 1.0;\n"
  "	};\n"
  "\n"
  "}; # end PhysicsParameters\n"
  "\n"
  "Initialization:\n"
  "{\n"
  "	ProblemType                    = 0;\n"
  "	ProblemTypeName                = \"\";\n"
  "	MBHParticleIO                  = False;\n"
  "	MBHParticleIOFilename          = \"mbh_particle_io.dat\";\n"
  "	MBHInsertLocationFilename      = \"mbh_insert_location.in\";\n"
  "	PartitionNestedGrids           = False;\n"
  "	StaticPartitionNestedGrids     = True;\n"
  "\n"
  "	StringKick                     = 0.0;\n"
  "	StringKickDimension            = 0;\n"
  "}; # end Initialization\n"
  "\n"
  "Analysis:\n"
  "{\n"
  "\n"
  "	Python:\n"
  "	{	\n"
  "		PythonTopGridSkip       = 0;\n"
  "		PythonSubcycleSkip      = 1;\n"
  "	};\n"
  "\n"
  "	HaloFinder:\n"
  "	{\n"
  "		InlineHaloFinder               = False;\n"
  "		HaloFinderSubfind              = False;\n"
  "		HaloFinderCycleSkip            = 3;\n"
  "		HaloFinderRunAfterOutput       = True;\n"
  "		HaloFinderOutputParticleList   = False;\n"
  "		HaloFinderMinimumSize          = 50;\n"
  "		HaloFinderLinkingLength        = 0.1;\n"
  "		HaloFinderTimestep             = 0.0;\n"
  "		HaloFinderLastTime             = 0.0;\n"
  "	};\n"
  "}; # end AnalysisParameters\n"
  "\n"
  "\n"
  "Problem:\n"
  "{\n"
  "	CollapseTest:\n"
  "	{\n"
  "		RefineAtStart = True;\n"
  "		UseParticles  = False;\n"
  "		ParticleMeanDensity = 0.0;\n"
  "		UseColour = False;\n"
  "		UseMetals = False;\n"
  "		InitialTemperature = 1000;\n"
  "		InitialDensity     = 1.0;\n"
  "\n"
  "		Spheres = [\"Sphere1\"];\n"
  "\n"
  "	        Sphere1:\n"
  "		{\n"
  "			Density = 1.0;\n"
  "			Temperature = 1.0;\n"
  "			Velocity = [0.0, 0.0, 0.0];\n"
  "		  	UniformVelocity = 0.0;\n"
  "			FracKeplerianRot = 0.0;\n"
  "		  	Turbulence = 0.0;\n"
  "		  	Dispersion = 0.0;\n"
  "		  	CutOff = 6.5;\n"
  "		  	Ang1 = 0.0;\n"
  "		  	Ang2 = 0.0;\n"
  "		  	Metallicity = 0.0;\n"
  "			NumShells = 1;\n"
  "		  	InitialLevel = 0;\n"
  "		  	Type = 0;\n"
  "			Radius = 1.0;\n"
  "			CoreRadius = 0.1;\n"
  "			Position = [0.5, 0.5, 0.5];\n"
  "		};\n"
  "	};\n"
  "\n"
  "	CosmologySimulation:\n"
  "	{\n"
  "		OmegaBaryonNow       = 1.0;\n"
  "		OmegaCDMNow          = 0.0;\n"
  "		InitialTemperature   = -99999.0;\n"
  " \n"
  "                DensityName           = \"\";\n"
  "		VelocitiesNames       = \"\";\n"
  "		TotalEnergyName       = \"\";\n"
  "		GasEnergyName         = \"\";\n"
  "		ParticlePositionName  = \"\";\n"
  "		ParticleVelocityName  = \"\";\n"
  "		ParticleDisplacementName = \"\";\n"
  "		ParticleMassName      = \"\";\n"
  "		ParticleTypeName      = \"\";\n"
  "		VelocityNames         = [\"\", \"\", \"\"];\n"
  "		ParticleVelocityNames = [\"\", \"\", \"\"];\n"
  "		ParticlePositionNames = [\"\", \"\", \"\"];\n"
  "		ParticleDisplacementNames = [\"\", \"\", \"\"];\n"
  "\n"
  "                InitialFractionHII   = 1.2e-5;\n"
  "		InitialFractionHeII  = 1.0e-14;\n"
  "		InitialFractionHeIII = 1.0e-17;\n"
  "		InitialFractionHM    = 2.0e-9;\n"
  "		InitialFractionH2I   = 2.0e-20;\n"
  "		InitialFractionH2II  = 3.0e-14;\n"
  "		InitialFractionMetal = 1.0e-10;\n"
  "		UseMetallicityField  = False;\n"
  " \n"
  "		ManuallySetParticleMassRatio = False;\n"
  "		ManualParticleMassRatio = 1.0;\n"
  "\n"
  "		CalculatePositions   = False; \n"
  "\n"
  "		InitialUniformBField = [0.0, 0.0, 0.0];  # in proper Gauss\n"
  "\n"
  "		RadHydroInitialRadiationEnergy = 1.0e-32;\n"
  "\n"
  "  		SubgridsAreStatic    = True;\n"
  "		InitialSubgrids = [];\n"
  "	};\n"
  "};\n"
  "";
